### ISSUE TITLE
Wing size, batteries and AUW

### ISSUE THREAD

**Issue by kikislater** [robustini/eXploraVTOL#3]
Hi,

Thanks for this great work ! 
Could you please display in your readme (or bom for batteries) common informations to have an idea of performances, like :
- wing span, (1320mm I guess ?)
- AUW with selected batteries
- Flight time in hover
- Flight time in flying wing mode
- batteries Voltage (6S ?), C rating, mAh and/or batteries used

Thanks

**Comment by robustini** [comment]
We still need to update the data, you can get this information on the Discord channel by comparing with those who are assembling it.

**Comment by kikislater** [comment]
@robustini thanks, unfortunately discord invitation has expired

**Comment by robustini** [comment]
https://discord.gg/TCjNnfAEsB

**Comment by kikislater** [comment]
thanks
