### ISSUE TITLE
add tilt rotors to front motors

### ISSUE THREAD

**Issue by stevereed66** [robustini/eXploraVTOL#4]
Hello,
Looks really good.
Not an issue,  are you planning on adding tilt rotor, gives much better  control in vtol mode.

I have  sidwinder 2 printer and have 3 tilt rotor  models eg  hee wing t1 ranger.

I  can setup arduplane as required.

If this is not in the plan  any idea's on modifications to nacles.There are lots of tilt mechanisms on thinki verse.

Thanks for great looking project

Steve

**Comment by robustini** [comment]
I do not rule out creating a configuration with tiltable motors as well, although with the published STEPs I was hoping that such a modification could be implemented by someone else.
