### ISSUE TITLE
CAD Files

### ISSUE THREAD

**Issue by gegner-io** [robustini/eXploraVTOL#6]
The files in Onshape seem to be imported. I cannot edit this file natively. Is there a way to access the original data? Possibly even SolidWorks files?

**Comment by robustini** [comment]
> The files in Onshape seem to be imported. I cannot edit this file natively. Is there a way to access the original data? Possibly even SolidWorks files?

I'm sorry but we don't release the original project in SolidWorks, only all the STEPs that are available here on GitHub.
